// <auto-generated />
using System;
using Gerenciamento_de_Tarefas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gerenciamento_de_Tarefas.Migrations
{
    [DbContext(typeof(GerenciadorTarefasContext))]
    partial class GerenciadorTarefasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gerenciamento_de_Tarefas.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.HasIndex("NomeCategoria")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Gerenciamento_de_Tarefas.Models.Tarefa", b =>
                {
                    b.Property<int>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarefaId"));

                    b.Property<bool>("Arquivada")
                        .IsUnicode(false)
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TarefaId");

                    b.HasIndex("Titulo")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("Gerenciamento_de_Tarefas.Models.TarefaEmCategoria", b =>
                {
                    b.Property<int>("TarefaEmCategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarefaEmCategoriaId"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("TarefaId")
                        .HasColumnType("int");

                    b.HasKey("TarefaEmCategoriaId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TarefaId");

                    b.ToTable("TarefasEmCategoria");
                });

            modelBuilder.Entity("Gerenciamento_de_Tarefas.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Gerenciamento_de_Tarefas.Models.Categoria", b =>
                {
                    b.HasOne("Gerenciamento_de_Tarefas.Models.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gerenciamento_de_Tarefas.Models.Tarefa", b =>
                {
                    b.HasOne("Gerenciamento_de_Tarefas.Models.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gerenciamento_de_Tarefas.Models.TarefaEmCategoria", b =>
                {
                    b.HasOne("Gerenciamento_de_Tarefas.Models.Categoria", "Categoria")
                        .WithMany("TarefasEmCategoria")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Gerenciamento_de_Tarefas.Models.Tarefa", "Tarefa")
                        .WithMany("TarefasEmCategorias")
                        .HasForeignKey("TarefaId");

                    b.Navigation("Categoria");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Gerenciamento_de_Tarefas.Models.Categoria", b =>
                {
                    b.Navigation("TarefasEmCategoria");
                });

            modelBuilder.Entity("Gerenciamento_de_Tarefas.Models.Tarefa", b =>
                {
                    b.Navigation("TarefasEmCategorias");
                });

            modelBuilder.Entity("Gerenciamento_de_Tarefas.Models.Usuario", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
